apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: nginx2
  labels:
    app: nginx2
spec:
  containers:
    - name: nginx2
      image: nginx
      imagePullPolicy: IfNotPresent
  restartPolicy: Always